[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cadcad"
authors = [{name = "Tyler Mace", email = "tyler@block.science"}]
dynamic = ["version", "description"]